AIUB_GamingFest_fatema/AIUB_GamingFest_fatema/Controllers/ManagerController.cs
using AIUB_GamingFest_fatema.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AIUB_GamingFest_fatema.Controllers
{
    public class ManagerController : Controller
    {
        // GET: Manager
        public ActionResult Volunteer_info()
        {
            finaltermEntities1 db = new finaltermEntities1();
            var data = db.volunteers.ToList();

            return View(data);
           
        }

        public ActionResult Conversation_with_Admin()
        {
            return View();
        }

        public ActionResult Logout()
        {
            return View();
        }

    }
}

AIUB_GamingFest_fatema/AIUB_GamingFest_fatema/Controllers/VolunteerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AIUB_GamingFest_fatema.Controllers
{
    public class VolunteerController : Controller
    {
        // GET: Volunteer
        public ActionResult Conversation_with_managers()
        {
            return View();
        }

        public ActionResult Logout()
        {
            return View();
        }
    }
}

AIUB_GamingFest_fatema/AIUB_GamingFest_fatema/Views/Dashboard_view.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

AIUB_GamingFest_fatema/AIUB_GamingFest_fatema/Views/LogRegiForgot_View.cshtml
<!DOCTYPE html>


<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>

	<link href="~/css/animate.css" rel="stylesheet" />
	<link href="~/css/bootstrap.css" rel="stylesheet" />
	<link href="~/css/bootstrap.min.css" rel="stylesheet" />
	<link href="~/css/chocolat.css" rel="stylesheet" />
	<link href="~/css/easy-responsive-tabs.css" rel="stylesheet" />
	<link href="~/css/font-awesome.css" rel="stylesheet" />
	<link href="~/css/style.css" rel="stylesheet" />



	<a href="~/fonts/fontawesome-webfont.eot"></a>
	<a href="~/fonts/fontawesome-webfont.ttf"></a>
	<a href="~/fonts/fontawesome-webfont.woff"></a>
	<a href="~/fonts/fontawesome-webfont.woff2"></a>
	<a href="~/fonts/FontAwesome.otf"></a>

</head>










<div class="banner">
	<div class="agileinfo-dot">
		<div class="agileits-logo">
			<h1><a href="https://localhost:44330/Home/Index">AIUB <span>GamingFest</span></a></h1>

		</div>
		</div>
	</div>
		<div class="header-top">
			<div class="container">
				<div class="header-top-info">
					<nav class="navbar navbar-default"></nav>
						<!-- Brand and toggle get grouped for better mobile display -->
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>

						</div>



						<!-- Collect the nav links, forms, and other content for toggling -->
						
						<!-- /.navbar-collapse -->
					

		

							<div class="clearfix"> </div>
							<script src="js/responsiveslides.min.js"></script>
							<script>
									// You can also use "$(window).load(function() {"
									$(function () {
									  // Slideshow 4
									  $("#slider4").responsiveSlides({
										auto: true,
										pager:true,
										nav:true,
										speed: 500,
										namespace: "callbacks",
										before: function () {
										  $('.events').append("<li>before event fired.</li>");
										},
										after: function () {
										  $('.events').append("<li>after event fired.</li>");
										}
									  });

									});
							</script>
							<!--banner Slider starts Here-->
						</div>
					</div>
			</div>

			




	<div>
		@RenderBody()
	</div>
	
				


<div class="copyright">
	<div class="container">
		<p class="footer-class">© 2017 Games Hub . All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">Fatema Tuz Zuhura</a> </p>
	</div>

</div>

AIUB_GamingFest_fatema/AIUB_GamingFest_fatema/Views/WebsiteView.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<link href="~/css/animate.css" rel="stylesheet" />
	<link href="~/css/bootstrap.css" rel="stylesheet" />
	<link href="~/css/bootstrap.min.css" rel="stylesheet" />
	<link href="~/css/chocolat.css" rel="stylesheet" />
	<link href="~/css/easy-responsive-tabs.css" rel="stylesheet" />
	<link href="~/css/font-awesome.css" rel="stylesheet" />
	<link href="~/css/style.css" rel="stylesheet" />

	

	<a href="~/fonts/fontawesome-webfont.eot"></a>
	<a href="~/fonts/fontawesome-webfont.ttf"></a>
	<a href="~/fonts/fontawesome-webfont.woff"></a>
	<a href="~/fonts/fontawesome-webfont.woff2"></a>
	<a href="~/fonts/FontAwesome.otf"></a>

	


</head>

<div class="banner">
	<div class="agileinfo-dot">
		<div class="agileits-logo">
			<h1><a href="https://localhost:44330/Home/Index">AIUB <span>GamingFest</span></a></h1>
			
		</div>
		<div class="header-top">
			<div class="container">
				<div class="header-top-info">
					<nav class="navbar navbar-default">
						<!-- Brand and toggle get grouped for better mobile display -->
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>



						<div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
							<nav>
								<ul class="nav navbar-nav">
									<li><a href="https://www.aiub.edu">About AIUB</a></li>
									<li>@Html.ActionLink("Previous Gaming Fest", "Previous_GamingFest", "Home", new { area = "" }, new { @class = "nav-link" }) </li>
									<li>@Html.ActionLink("LogIn", "LogIn", "Home", new { area = "" }, new { @class = "nav-link" }) </li>

									<!----<li><a href="Index.cshtml" class="scroll">About</a></li>-->

								</ul>
							</nav><!-- Collect the nav links, forms, and other content for toggling -->

						</div>
						<!-- /.navbar-collapse -->
					</nav>
				</div>
			</div>
		</div>
		<div class="w3layouts-banner-info">
			<div class="container">
				<div class="w3layouts-banner-slider">
					<div class="w3layouts-banner-top-slider">
						<div class="slider">
							<div class="callbacks_container">
								<ul class="rslides callbacks callbacks1" id="slider4">
									<li>

										<div>
											<h2>Registration Open</h2>

											<div class="w3-button">
												<a href="https://localhost:44330/Home/Registration2" data-toggle="modal" data-target="#myModal">Click For Registration</a>
												<p>
								
</div>
									   </div>
									</li>
									
								</ul>
							</div>
							<div class="clearfix"> </div>
							<script src="js/responsiveslides.min.js"></script>
							<script>
									// You can also use "$(window).load(function() {"
									$(function () {
									  // Slideshow 4
									  $("#slider4").responsiveSlides({
										auto: true,
										pager:true,
										nav:true,
										speed: 500,
										namespace: "callbacks",
										before: function () {
										  $('.events').append("<li>before event fired.</li>");
										},
										after: function () {
										  $('.events').append("<li>after event fired.</li>");
										}
									  });

									});
							</script>
							<!--banner Slider starts Here-->
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>



<body>
	<div>
		@RenderBody()
	</div>
	<div class="footer">
		<div class="container">
			<div class="footer-top">
				<div class="col-md-4 amet-sed">
					<div class="footer-title">
						
					</div>
					<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
				</div>
				<div class="col-md-4 amet-sed amet-medium">
					<div class="footer-title">
						<h3>Twitter Feed</h3>
					</div>
					<p><a href="#">http://example.com</a> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt lorem sed velit fermentum eget placerat. </p>
					<p><a href="#">http://mail.com</a> Sed tincidunt lorem sed velit fermentum eget placerat. Lorem ipsum dolor sit, consectetur adipiscing elit. </p>
				</div>
				<div class="col-md-4 amet-sed ">
					<div class="footer-title">
						<h3>Follow Us</h3>
					</div>
					<div class="agileinfo-social-grids">
						<ul>
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-rss"></i></a></li>
							<li><a href="#"><i class="fa fa-vk"></i></a></li>
						</ul>
					</div>
					<div class="support">
						<form action="#" method="post">
							<input type="email" placeholder="Enter email...." required="">
							<input type="submit" value="Subscribe" class="botton">
						</form>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
</body>
<div class="copyright">
	<div class="container">
		<p class="footer-class">© 2017 Games Hub . All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">Fatema Tuz Zuhura</a> </p>
	</div>
	
</div>
</html>

AIUB_GamingFest_fatema/AIUB_GamingFest_fatema/Views/managerlayout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")



</head>

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
	<div class="container">
		@Html.ActionLink("Conversation with Admin", "Conversation_with_Admin", "Manager", new { area = "" }, new { @class = "navbar-brand" })
		<button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
				aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
			<ul class="navbar-nav flex-grow-1">

				
				<li>@Html.ActionLink("Volunteers Information", "Volunteer_info", "Manager", new { area = "" }, new { @class = "nav-link" })</li>
				<li>@Html.ActionLink("Logout", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
			</ul>
		</div>
	</div>
</nav>
<body>
	<div>
		@RenderBody()
	</div>


	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>

AIUB_GamingFest_fatema/AIUB_GamingFest_fatema/Views/volunteerlayout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")

</head>
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
	<div class="container">
		@Html.ActionLink("Conversation with manager", "Conversation_with_managers", "Volunteer", new { area = "" }, new { @class = "navbar-brand" })
		<button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
				aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
			<ul class="navbar-nav flex-grow-1">


				
				<li>@Html.ActionLink("Logout", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
			</ul>
		</div>
	</div>
</nav>
<body>
	<div>
		@RenderBody()
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>